require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'macOS' do
  platform :macos, '15.0'
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Sparkle'
  pod 'HotKey'

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_EXPERIMENTAL_EXPLICIT_MODULES'] = 'NO'
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end

end
