default_platform(:mac)

platform :mac do

  lane :release do
    Dir.chdir("..") do
      sh("bun", "bump")
    end

    version = get_version_number(xcodeproj: "./macos/insig8.xcodeproj")

    path = "/Users/neel/Desktop/AI Experiments/Private Notetaker/JetBrains/insig8"
    appFileName = path + "Insig8.app"
    zipFileName = path + "releases/" + version + ".zip"

    gym(
      scheme: "release",
      configuration: "Release",
      clean: true,
      workspace: "./macos/insig8.xcworkspace",
      output_directory: path,
      export_method: "developer-id"
    )

    notarize(
      package: appFileName,
      bundle_id: "com.insig8.insig8",
      username: "neelprivate@gmail.com",
      asc_provider: "24CMR7378R"
    )

    zip(
      path: appFileName,
      output_path: zipFileName,
      symlinks: true
    )

    set_github_release(
      repository_name: "njthakker/insig8",
      api_token: ENV["GITHUB_API_TOKEN"],
      name: "v" + version,
      tag_name: version,
      description: "No release notes provided.",
      upload_assets: [zipFileName]
    )

    file_url = "https://github.com/njthakker/insig8/releases/download/" + version + "/" + version + ".zip"


    Dir.chdir("..") do
      sh("bun", "appcast")

      sh("./scripts/appcast.sh", file_url, version)

      Dir.glob("#{path}releases/*.zip").each { |file| File.delete(file) }

      sh("git", "add", ".")
      sh("git", "commit", "-m", version)
      sh("git", "push")
    end

    sh("cp", "-R", appFileName, "/Applications/")

    sh("open", "/Applications/Insig8.app")

    sh("pingme", "Insig8 " + version + " released")
  end
end
